"use client"

import './globals.css'
import * as React from 'react';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';

import SideMenu from './template/sidemenu/drawer'
import Header from './template/header'

const metadata = {
    title: 'Nextjs MUI',
    description: 'Generated by create next app',
}
  
function RootLayout(props) {
    const [mobileOpen, setMobileOpen] = React.useState(false);

    return (
        <html lang="en">
            <head>
                <title>{metadata.title}</title>
                <meta name={metadata.description} content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <Box sx={{ display: 'flex' }}>
                    <CssBaseline />
                    <Header mobileOpen={mobileOpen} setMobileOpen={setMobileOpen}/>
                    <SideMenu mobileOpen={mobileOpen} setMobileOpen={setMobileOpen}/>
                    <div className='mt-content'>{props.children}</div>
                </Box>
            </body>
        </html>
    );
}

export default RootLayout;